### ISSUE TITLE
roles using eos_config and a regexp seem to flag a change on every run

### ISSUE THREAD

**Issue by perimore** [arista-eosplus/ansible-eos-playbooks#1]
I think the regexp is incorrect. Take the regex below:

```
regexp='(?<=[^no ] )bgp log-neighbor-changes'
```

This is using  positive lookbehind to match the 'no' form of the command. I think we should be matching bgp log-neighbor-changes as long as it doesn't have 'no'. And there seems to be an issue with defining 'no' as the start of string. Using the below I find works:

regexp='(?<!no )bgp log-neighbor-changes'

I.e. match 'bgp log-neighbor-changes' as long as 'no' is not present.

Square brackets are also matching any of 'n','o' or ' '

**Comment by phil-dileo** [comment]
Consider the example from the docs:

```
- name: configure interface range to be shutdown if it isn't already
  eos_config:
    command='shutdown'
    regexp='(?<=[^no ] )shutdown'
    section='interface {{ item }}'
  with_items:
    - Ethernet1
    - Ethernet2
    - Ethernet3
```

^ This says: look for `no shutdown` and if you find it, execute `shutdown`

The purpose of regex is to find an existing piece of config and then use `command` to execute the desired config command.

So for the case of bgp log-neighbor-changes, we want to use regexp to find the no version and run `bgp log-neighbor-changes` if we find it.

**Comment by phil-dileo** [comment]
Forget my nonsense. You're correct! I'll update the regexp used. Thanks!!!
