### ISSUE TITLE
MLAG peer-link name striped 

### ISSUE THREAD

**Issue by perimore** [arista-eosplus/ansible-eos-playbooks#2]
MLAG config is always marked as a change. I can see the peer_link is read as 'Port' rather than 'Port-Channel10'. Not sure if this is a bug in the Ansible module or the playbook.

changed: [leaf2] => {"changed": true, "changes": {"peer_link": "Port-Channel10"}, "debug": {"current_state": {"domain_id": "mlag1", "local_interface": "Vlan1024", "peer_address": "10.0.0.1", "peer_link": "Port", "shutdown": false}, "desired_state": {"domain_id": "mlag1", "local_interface": "Vlan1024", "peer_address": "10.0.0.1", "peer_link": "Port-Channel10", "shutdown": false}

**Comment by phil-dileo** [comment]
Yup, there's a fix for this in pyeapi, in the develop branch.
Ref: https://github.com/arista-eosplus/pyeapi/issues/24
