### ISSUE TITLE
Interface address read as Null when ipinterface also has eos_switchports attributes

### ISSUE THREAD

**Issue by perimore** [arista-eosplus/ansible-eos-playbooks#3]
Noticed that the ip address of interfaces is always read as null on the playbook run. But when the eos_switchports trunk attributes are removed, it works fine.

With eos_switchports:

eos_switchports:
- name: Ethernet1
  mode: trunk

ip_interfaces:
- name: Loopback0
  address: 1.1.1.10/32
- name: Ethernet1
  address: 100.1.1.1/31

changed: [leaf1] => (item={'name': 'Ethernet1', 'address': '10.1.1.1/31'}) => {"changed": true, "changes": {"address": "10.1.1.1/31"}, "debug": {"current_state": {"address": null, "mtu": "1500", "name": "Ethernet1", "state": "present"}, "desired_state": {"address": "10.1.1.1/31", "mtu": null, "name": "Ethernet1", "state": "present"}, "eos_model": "vEOS", "eos_version": "4.15.0F", "node": "Node(connection=EapiConnection(transport=https://leaf1:443//command-api))", "params": {"address": "10.1.1.1/31", "config": null, "connection": "leaf1", "debug": true, "host": null, "logging": true, "mtu": null, "name": "Ethernet1", "password": null, "port": null, "state": "present", "transport": null, "username": null}, "pyeapi_version": "develop", "stateful": true}, "instance": {"address": "10.1.1.1/31", "mtu": "1500", "name": "Ethernet1", "state": "present"}, "item": {"address": "10.1.1.1/31", "name": "Ethernet1"}}

Remove the eos_switchports part and this works.

**Comment by phil-dileo** [comment]
Right, this was fixed in
https://github.com/arista-eosplus/ansible-eos-playbooks/commit/f16425f1d828257e19a9618c8385077ed356ab1a

Thanks
